### ISSUE TITLE
depth loss calculation error

### ISSUE THREAD

**Issue by tgeorgy** [DavyNeven/fastSceneUnderstanding#11]
I think you have an error here
https://github.com/DavyNeven/fastSceneUnderstanding/blob/2129e4cde7e44bd2368e6d45861a743f95121bab/lossf/myHuberLoss.lua#L12

It should be torch.lt() as you need L1 for large values and L2 for small

**Comment by davyneven** [comment]
We use the reverse Huber Loss (Berhu loss), which uses L1 for small errors and L2 for big ones. So it should be correct as is.

**Comment by tgeorgy** [comment]
Got it, thank you!
