### ISSUE TITLE
Your code support Multi GPU training or not?

### ISSUE THREAD

**Issue by gaopeng-eugene** [DavyNeven/fastSceneUnderstanding#3]
It seems that you use iter to increase the real batch size. The multi GPU part in your code work or not?

**Comment by DavyNeven** [comment]
It does support multi GPU training, by setting the option -nGPU to the number op GPUs you want to train on. However, in case you don't have multiple GPUs, you can indeed increase the -iterSize option to "fake" a higher batchsize.
