### ISSUE TITLE
Models in download.sh

### ISSUE THREAD

**Issue by li-js** [DavyNeven/fastSceneUnderstanding#7]
Hi @DavyNeven @dbbert 

Nice work and thanks for sharing the code. 

I have a question about the trained model here:
http://esat.kuleuven.be/~dneven/data/fastSceneSegmentation/fastSceneSegmentationFinal.t7. 

Since we have: 
local labels_inst = cluster.cluster(out_instances, labels_segm:eq(15), 1.5),
does this model only contain the predicted instance information for cars? For the instance prediction for other classes, do we have to use some other model, or we can simply change 15 to some other class id?

**Comment by DavyNeven** [comment]
Indeed, the model is only trained for instance segmentation on the car class. If you would also like to train for the other classes as well, you can modify the dataloader to also load the instances for the other classes ( see datasets/Cityscapes.lua 76 - 83). Where the returned instance map is now a 1 x 256 x 512 tensor, it would then become a N x 256 x 512 tensor. Normally the code can perfectly handle this change.

**Comment by li-js** [comment]
Thanks for the reply. 

Since the paper reports mean AP,  there should be some other trained models. Is there a plan to release the additional models other than Car?

**Comment by DavyNeven** [comment]
This repository is primarily meant for reproducing the results for the "Fast Scene Understanding for Autonomous Driving" paper, which only reports AP for the car class.
